### ISSUE TITLE
Unit Test : Add weird type test

### ISSUE THREAD

**Issue by carpaltunnel** [carpaltunnel/arca-github-2023#2]
At https://github.com/carpaltunnel/arca-github-2023/blob/main/test/test.js#L14

`toBe(3)` should be `toBe(Number(1 + 3))`.  

Update
`expect(3).toBe(2);`
and change it to 
`expect(3).toBe(Number(1 + 3));`

**Comment by 711jackkelley** [comment]
Hello, I'd like to contribute to this issue. Is the fix only needed in the file linked or are there other places as well?
